ROUTE = {
 "Cap": [],
 "Cascade": [("Our First Power Moon", "Multi Moon Atop the Falls"),
             ("Multi Moon Atop the Falls", "Treasure of the Waterfall Basin")],
 "Sand": [("Treasure of the Waterfall Basin", "Overlooking the Desert Town"),
          ("Overlooking the Desert Town", "Bird Traveling the Desert"),
          ("Bird Traveling the Desert", "A Rumble from the Sandy Floor"),
          ("A Rumble from the Sandy Floor", "Hidden Room in the Flowing Sands"),
          ("Hidden Room in the Flowing Sands", "Sphynx's Treasure Vault"),
          ("Sphynx's Treasure Vault", "Lost in the Luggage"),
          ("Lost in the Luggage", "Secret of the Inverted Mural"),
          ("Secret of the Inverted Mural", "Hidden Room in the Inverted Pyramid"),
          ("Hidden Room in the Inverted Pyramid", "On the Statue's Tail"),
          ("On the Statue's Tail", "Showdown on the Inverted Pyramid"),
          ("Showdown on the Inverted Pyramid", "Sand Kingdom Slots"),
          ("Sand Kingdom Slots", "Atop the Highest Tower"),
          ("Atop the Highest Tower", "Goomba Tower Assembly"),
          ("Goomba Tower Assembly", "Underground Treasure Chest"),
          ("Underground Treasure Chest", "The Hole in the Desert")],
 "Wooded": [("The Hole in the Desert", "Beneath the Roots of a Moving Tree"),
            ("Beneath the Roots of a Moving Tree", "Glowing in the Deep Woods"),
            ("Glowing in the Deep Woods", "The Hard Rock in Deep Woods"),
            ("The Hard Rock in Deep Woods", "Rolling Rock in the Deep Woods"),
            ("Rolling Rock in the Deep Woods", "By the Babbling Brook in the Deep Woods"),
            ("By the Babbling Brook in the Deep Woods", "Atop a Tall Tree"),
            ("Atop a Tall Tree", "Tucked Away Inside a Tunnel"),
            ("Tucked Away Inside a Tunnel", "Climb the Cliff to Get the Nut"),
            ("Climb the Cliff to Get the Nut", "The Nut at the Dead End"),
            ("The Nut at the Dead End", "Road to Sky Garden"),
            ("Road to Sky Garden", "Cracked Nut on a Crumbling Tower"),
            ("Cracked Nut on a Crumbling Tower", "Nut Planted in the Tower"),
            ("Nut Planted in the Tower", "Stretching Your Legs"),
            ("Stretching Your Legs", "Flower Thieves of Sky Garden")],
 "Lake": [("Flower Thieves of Sky Garden", "End of the Hidden Passage"),
          ("End of the Hidden Passage", "Cheep Cheep Crossing"),
          ("Cheep Cheep Crossing", "Dorrie-Back Rider"),
          ("Dorrie-Back Rider", "From the Broken Pillar"),
          ("From the Broken Pillar", "Broodals Over the Lake"),
          ("Broodals Over the Lake", "On the Lakeshore")],
 "Cloud": [],
 "Lost": [("On the Lakeshore", "On the Mountain Road"),
          ("On the Mountain Road", "A Butterfly's Treasure"),
          ("A Butterfly's Treasure", "Over the Fuzzies, Above the Swamp"),
          ("Over the Fuzzies, Above the Swamp", "Avoiding Fuzzies Inside the Wall"),
          ("Avoiding Fuzzies Inside the Wall", "Enjoying the View of Forgotten Isle"),
          ("Enjoying the View of Forgotten Isle", "Cave Gardening"),
          ("Cave Gardening", "On a Tree in the Swamp"),
          ("On a Tree in the Swamp", "Inside the Stone Cage"),
          ("Inside the Stone Cage", "The Caged Gold"),
          ("The Caged Gold", "Peeking Out from Under the Bridge"),
          ("Peeking Out from Under the Bridge", "Soaring Over the Forgotten Isle!"),
          ("Soaring Over the Forgotten Isle!", "Twist ‘n' Turn-Up Treasure")],
 "Metro": [("Twist ‘n' Turn-Up Treasure", "Girder Sandwich"),
           ("Girder Sandwich", "Swaying in the Breeze"),
           ("Swaying in the Breeze", "City Hall Lost & Found"),
           ("City Hall Lost & Found", "New Donk City's Pest Problem"),
           ("New Donk City's Pest Problem", "Secret Girder Tunnel!"),
           ("Secret Girder Tunnel!", "Bench Friends"),
           ("Bench Friends", "Drummer on Board!"),
           ("Drummer on Board!", "Bassist on Board!"),
           ("Bassist on Board!", "Guitarist on Board!"),
           ("Guitarist on Board!", "Glittering Above the Pool"),
           ("Glittering Above the Pool", "Left at the Cafe?"),
           ("Left at the Cafe?", "Trumpeter on Board!"),
           ("Trumpeter on Board!", "Sewer Treasure"),
           ("Sewer Treasure", "Powering Up the Station"),
           ("Powering Up the Station", "Celebrating in the Streets!"),
           ("Celebrating in the Streets!", "A Traditional Festival!"),
           ("A Traditional Festival!", "A Tourist in the Metro Kingdom!")],
 "Snow": [("A Tourist in the Metro Kingdom!", "Entrance to Shiveria"),
          ("Entrance to Shiveria", "Shopping in Shiveria"),
          ("Shopping in Shiveria", "The Shiverian Treasure Chest"),
          ("The Shiverian Treasure Chest", "Shining in the Snow in Town"),
          ("Shining in the Snow in Town", "The Bound Bowl Grand Prix"),
          ("The Bound Bowl Grand Prix", "Snow Kingdom Timer Challenge 2"),
          ("Snow Kingdom Timer Challenge 2", "Caught Hopping in the Snow!"),
          ("Caught Hopping in the Snow!", "Fishing in the Glacier!")],
 "Seaside": [("Fishing in the Glacier!", "A Rumble on the Seaside Floor"),
             ("A Rumble on the Seaside Floor", "The Stone Pillar Seal"),
             ("The Stone Pillar Seal", "The Lighthouse Seal"),
             ("The Lighthouse Seal", "Ride the Jetstream"),
             ("Ride the Jetstream", "On the Cliff Overlooking the Beach"),
             ("On the Cliff Overlooking the Beach", "Good Job, Captain Toad!"),
             ("Good Job, Captain Toad!", "The Seal Above the Canyon"),
             ("The Seal Above the Canyon", "The Back Canyon: Excavate!"),
             ("The Back Canyon: Excavate!", "What the Waves Left Behind"),
             ("What the Waves Left Behind", "The Hot Spring Seal"),
             ("The Hot Spring Seal", "Taking Notes: Ocean Surface Dash"),
             ("Taking Notes: Ocean Surface Dash", "The Glass Is Half Full!")],
 "Luncheon": [("The Glass Is Half Full!", "Luncheon Kingdom Timer Challenge 1"),
              ("Luncheon Kingdom Timer Challenge 1", "The Broodals Are After Some Cookin'"),
              ("The Broodals Are After Some Cookin'", "Under the Cheese Rocks"),
              ("Under the Cheese Rocks", "Light the Lantern on the Small Island"),
              ("Light the Lantern on the Small Island", "Crossing to the Magma"),
              ("Crossing to the Magma", "Magma Narrow Path"),
              ("Magma Narrow Path", "Surrounded by Tall Mountains"),
              ("Surrounded by Tall Mountains", "Big Pot on the Volcano: Dive In!"),
              ("Big Pot on the Volcano: Dive In!", "The Treasure Chest in the Veggies"),
              ("The Treasure Chest in the Veggies", "Overlooking a Bunch of Ingredients"),
              ("Overlooking a Bunch of Ingredients", "Alcove Behind the Pillars of Magma"),
              ("Alcove Behind the Pillars of Magma", "Climb Up the Cascading Magma"),
              ("Climb Up the Cascading Magma", "Light the Far-Off Lanterns"),
              ("Light the Far-Off Lanterns", "Cookatiel Showdown!")],
 "Ruined": [("Cookatiel Showdown!", "In the Ancient Treasure Chest"),
            ("In the Ancient Treasure Chest", "Battle with the Lord of Lightning!")],
 "Bowser": [("Battle with the Lord of Lightning!", "Behind the Big Wall"),
            ("Behind the Big Wall", "Infiltrate Bowser's Castle"),
            ("Infiltrate Bowser's Castle", "Poking the Turret Wall"),
            ("Poking the Turret Wall", "Treasure Inside the Turret"),
            ("Treasure Inside the Turret", "Smart Bombing"),
            ("Smart Bombing", "From the Side above the Castle Gate"),
            ("From the Side above the Castle Gate", "Jizo All in a Row"),
            ("Jizo All in a Row", "Underground Jizo"),
            ("Underground Jizo", "Big Broodal Battle"),
            ("Big Broodal Battle", "Hidden Corridor Under the Floor"),
            ("Hidden Corridor Under the Floor", "Good to See You, Captain Toad!"),
            ("Good to See You, Captain Toad!", "Inside a Block in the Castle"),
            ("Inside a Block in the Castle", "Poking Your Nose by the Great Gate"),
            ("Poking Your Nose by the Great Gate", "On the Giant Bowser Statue's Nose"),
            ("On the Giant Bowser Statue's Nose", "Showdown at Bowser's Castle"),
            ("Showdown at Bowser's Castle", "Caught on the Iron Fence")],
 "Moon": [("Caught on the Iron Fence", "Caught Hopping on the Moon!"),
          ("Caught Hopping on the Moon!", "Rolling Rock on the Moon"),
          ("Rolling Rock on the Moon", "Cliffside Treasure Chest"),
          ("Cliffside Treasure Chest", "The Tip of a White Spire"),
          ("The Tip of a White Spire", "Up in the Rafters")],
 "Mushroom": [("Up in the Rafters", "Light from the Ceiling"),
              ("Light from the Ceiling", "Loose-Tile Trackdown"),
              ("Loose-Tile Trackdown", "Pops out of the Tail")],
 "Snow 2": [("Pops out of the Tail", "Secret Path to Shiveria!"),
            ("Secret Path to Shiveria!", "Captain Toad is Chilly!"),
            ("Captain Toad is Chilly!", "Taking Notes: Snow Path Dash"),
            ("Taking Notes: Snow Path Dash", "Snow Kingdom Timer Challenge 1"),
            ("Snow Kingdom Timer Challenge 1", "Above the Freezing Fish Pond"),
            ("Above the Freezing Fish Pond", "Ice Floe Swimming"),
            ("Ice Floe Swimming", "Deep in the Cold, Cold Water"),
            ("Deep in the Cold, Cold Water", "Snow Kingdom Timer Challenge 3"),
            ("Snow Kingdom Timer Challenge 3", "Shining on High"),
            ("Shining on High", "It Popped Out of the Ice"),
            ("It Popped Out of the Ice", "Peach in the Snow Kingdom"),
            ("Peach in the Snow Kingdom", "Icy Jump Challenge"),
            ("Icy Jump Challenge", "Atop a Blustery Arch"),
            ("Atop a Blustery Arch", "The Gusty Barrier"),
            ("The Gusty Barrier", "Behind the Snowy Mountain"),
            ("Behind the Snowy Mountain", "Squirming Under the Ice"),
            ("Squirming Under the Ice", "The Snowy Mountain Barrier"),
            ("The Snowy Mountain Barrier", "Water Pooling in the Crevasse"),
            ("Water Pooling in the Crevasse", "Treasure in the Ice Wall"),
            ("Treasure in the Ice Wall", "The Ice Wall Barrier"),
            ("The Ice Wall Barrier", "Hat-and-Seek in the Snow"),
            ("Hat-and-Seek in the Snow", "Forgotten in the Holding Room")],
 "Cascade 2": [("Forgotten in the Holding Room", "Secret Path to Fossil Falls!"),
               ("Secret Path to Fossil Falls!", "Above a High Cliff"),
               ("Above a High Cliff", "Good Morning, Captain Toad!"),
               ("Good Morning, Captain Toad!", "Chomp Through the Rocks"),
               ("Chomp Through the Rocks", "Atop a Wall Among the Clouds"),
               ("Atop a Wall Among the Clouds", "Across the Mysterious Clouds"),
               ("Across the Mysterious Clouds", "Treasure Under the Cliff"),
               ("Treasure Under the Cliff", "Just a Hat, Skip, and a Jump"),
               ("Just a Hat, Skip, and a Jump", "Behind the Waterfall"),
               ("Behind the Waterfall", "Taking Notes: Hurry Upward"),
               ("Taking Notes: Hurry Upward", "Peach in the Cascade Kingdom"),
               ("Peach in the Cascade Kingdom", "Inside the Busted Fossil"),
               ("Inside the Busted Fossil", "Guarded by a Colossal Fossil"),
               ("Guarded by a Colossal Fossil", "Next to the Stone Arch"),
               ("Next to the Stone Arch", "Cascade Kingdom Timer Challenge 2"),
               ("Cascade Kingdom Timer Challenge 2", "Across the Floating Isles"),
               ("Across the Floating Isles", "Under the Ground"),
               ("Under the Ground", "Rolling Rock by the Falls"),
               ("Rolling Rock by the Falls", "Under the Old Electrical Pole"),
               ("Under the Old Electrical Pole", "Found with Lake Kingdom Art"),
               ("Found with Lake Kingdom Art", "A Tourist in the Cascade Kingdom"),
               ("A Tourist in the Cascade Kingdom", "On Top of the Rubble"),
               ("On Top of the Rubble", "Shopping in Fossil Falls"),
               ("Shopping in Fossil Falls", "Caught Hopping at the Waterfall!"),
               ("Caught Hopping at the Waterfall!", "Cascade Kingdom Timer Challenge 1"),
               ("Cascade Kingdom Timer Challenge 1", "Bottom of the Waterfall Basin")],
 "Bowser 2": [("Bottom of the Waterfall Basin", "Secret Path to Bowser's Castle"),
              ("Secret Path to Bowser's Castle", "Bowser's Castle Treasure Vault"),
              ("Bowser's Castle Treasure Vault", "Found Behind Bars!"),
              ("Found Behind Bars!", "From Crates in the Moat"),
              ("From Crates in the Moat", "Sunken Treasure in the Moat"),
              ("Sunken Treasure in the Moat", "Above the Poison Swamp"),
              ("Above the Poison Swamp", "Knocking Down the Nice Frame"),
              ("Knocking Down the Nice Frame", "Caught Hopping at Bowser's Castle!"),
              ("Caught Hopping at Bowser's Castle!", "Caught on the Giant Horn"),
              ("Caught on the Giant Horn", "A Rumble Under the Arena Floor"),
              ("A Rumble Under the Arena Floor", "Bowser's Kingdom Timer Challenge 1"),
              ("Bowser's Kingdom Timer Challenge 1", "Jizo and the Hidden Room"),
              ("Jizo and the Hidden Room", "Jizo's Big Adventure"),
              ("Jizo's Big Adventure", "Peach in Bowser's Kingdom"),
              ("Peach in Bowser's Kingdom", "Shopping at Bowser's Castle"),
              ("Shopping at Bowser's Castle", "Third Courtyard Outskirts"),
              ("Third Courtyard Outskirts", "Taking notes: Between spinies"),
              ("Taking notes: Between spinies", "Poking Your Nose in the Plaster Wall"),
              ("Poking Your Nose in the Plaster Wall", "Taking Notes: On the Wall"),
              ("Taking Notes: On the Wall", "Small Bird in Bowser's Castle"),
              ("Small Bird in Bowser's Castle", "Past the Moving Wall"),
              ("Past the Moving Wall", "Invader in Bowser's Castle")],
 "Seaside 2": [("Invader in Bowser's Castle", "Secret Path to Bubblaine"),
               ("Secret Path to Bubblaine", "Sea Gardening: Inlet Seed"),
               ("Sea Gardening: Inlet Seed", "Above the Parasol: Catch!"),
               ("Above the Parasol: Catch!", "Treasure Trap Hidden in the Inlet"),
               ("Treasure Trap Hidden in the Inlet", "A Light Next to the Lighthouse"),
               ("A Light Next to the Lighthouse", "At the Base of the Lighthouse"),
               ("At the Base of the Lighthouse", "Bird Traveling Over the Ocean"),
               ("Bird Traveling Over the Ocean", "Bonjour, Dorrie!"),
               ("Bonjour, Dorrie!", "Shopping in Bubblaine"),
               ("Shopping in Bubblaine", "Underwater Highway Tunnel"),
               ("Underwater Highway Tunnel", "Underwater Highway West: Explore!"),
               ("Underwater Highway West: Explore!", "Found with Luncheon Kingdom Art"),
               ("Found with Luncheon Kingdom Art", "The Tall Rock Shell in the Deep Ocean"),
               ("The Tall Rock Shell in the Deep Ocean", "Under a Dangerous Ceiling"),
               ("Under a Dangerous Ceiling", "Merci, Dorrie!"),
               ("Merci, Dorrie!", "Bubblaine Northern Reaches"),
               ("Bubblaine Northern Reaches", "Gap in the Ocean Trench"),
               ("Gap in the Ocean Trench", "The Sphynx's Underwater Vault"),
               ("The Sphynx's Underwater Vault", "A Fine Detail on the Glass"),
               ("A Fine Detail on the Glass", "Caught Hopping at Glass Palace!"),
               ("Caught Hopping at Glass Palace!", "Lighthouse Leaper"),
               ("Lighthouse Leaper", "Ocean-Bottom Maze: Hidden Room"),
               ("Ocean-Bottom Maze: Hidden Room", "Taking Notes: Ocean-Bottom Maze"),
               ("Taking Notes: Ocean-Bottom Maze", "Ocean-Bottom Maze: Treasure"),
               ("Ocean-Bottom Maze: Treasure", "Glass Palace Treasure Chest"),
               ("Glass Palace Treasure Chest", "Shh! It's a Shortcut!"),
               ("Shh! It's a Shortcut!", "Slip Through the Nesting Spot"),
               ("Slip Through the Nesting Spot", "Underwater Highway East: Explore!"),
               ("Underwater Highway East: Explore!", "Rapid Ascent on Hot Spring Island"),
               ("Rapid Ascent on Hot Spring Island", "Peach in the Seaside Kingdom"),
               ("Peach in the Seaside Kingdom", "What Shines Inside the Glass")],
 "Wooded 2": [("What Shines Inside the Glass", "Secret Path to the Steam Gardens"),
              ("Secret Path to the Steam Gardens", "The Nut that Grew on the Tall Fence"),
              ("The Nut that Grew on the Tall Fence", "Path to the Secret Flower Field"),
              ("Path to the Secret Flower Field", "Defend the Secret Flower Field!"),
              ("Defend the Secret Flower Field!", "Rolling Rock in the Woods"),
              ("Rolling Rock in the Woods", "Caught Hopping in the Forest!"),
              ("Caught Hopping in the Forest!", "Shopping in Steam Gardens"),
              ("Shopping in Steam Gardens", "Looking Down on the Goombas"),
              ("Looking Down on the Goombas", "Lost in the Tall Trees"),
              ("Lost in the Tall Trees", "Behind the Rock Wall"),
              ("Behind the Rock Wall", "Hey Out There, Captain Toad!"),
              ("Hey Out There, Captain Toad!", "Over the Cliff's Edge"),
              ("Over the Cliff's Edge", "Love in the Forest Ruins"),
              ("Love in the Forest Ruins", "The Nut ‘Round The Corner"),
              ("The Nut ‘Round The Corner", "The Nut in the Robot Storeroom"),
              ("The Nut in the Robot Storeroom", "High Up in the Cave"),
              ("High Up in the Cave", "Flood Pipeway Ceiling Secret"),
              ("Flood Pipeway Ceiling Secret", "Flooding Pipeway"),
              ("Flooding Pipeway", "Peach in the Wooded Kingdom"),
              ("Peach in the Wooded Kingdom", "The Nut Under the Observation Deck"),
              ("The Nut Under the Observation Deck", "Above the Iron Mountain Path"),
              ("Above the Iron Mountain Path", "High Up on a Rock Wall"),
              ("High Up on a Rock Wall", "The Nut in the Red Maze"),
              ("The Nut in the Red Maze", "Moon Shards in the Forest"),
              ("Moon Shards in the Forest", "Wooded Kingdom Timer Challenge 1"),
              ("Wooded Kingdom Timer Challenge 1", "Bird Traveling the Forest"),
              ("Bird Traveling the Forest", "Fire in the Cave"),
              ("Fire in the Cave", "Below Breakdown Road"),
              ("Below Breakdown Road", "Down and Back Breakdown Road"),
              ("Down and Back Breakdown Road", "Wooded Kingdom Timer Challenge 3"),
              ("Wooded Kingdom Timer Challenge 3", "Thanks for the Charge!"),
              ("Thanks for the Charge!", "Wooded Kingdom Timer Challenge 2")],
 "Sand 2": [("Wooded Kingdom Timer Challenge 2", "Secret Path to Tostarena!"),
            ("Secret Path to Tostarena!", "Top of a Dune"),
            ("Top of a Dune", "Caught Hopping in the Desert!"),
            ("Caught Hopping in the Desert!", "Hat-and-Seek: In the Sand"),
            ("Hat-and-Seek: In the Sand", "Jammin' in the Sand Kingdom"),
            ("Jammin' in the Sand Kingdom", "Hang Your Hat on the Fountain"),
            ("Hang Your Hat on the Fountain", "Desert Gardening: Plaza Seed"),
            ("Desert Gardening: Plaza Seed", "Found in the Sand! Good Dog!"),
            ("Found in the Sand! Good Dog!", "Employees Only"),
            ("Employees Only", "On Top of Stone Archway"),
            ("On Top of Stone Archway", "Love in the Heart of the Desert"),
            ("Love in the Heart of the Desert", "Bullet Bill Breakthrough"),
            ("Bullet Bill Breakthrough", "Inside a Block Is a Hard Place"),
            ("Inside a Block Is a Hard Place", "On the Leaning Pillar"),
            ("On the Leaning Pillar", "On the Eastern Pillar"),
            ("On the Eastern Pillar", "The Treasure of Jaxi Ruins"),
            ("The Treasure of Jaxi Ruins", "Bird Traveling Wastes"),
            ("Bird Traveling Wastes", "Island in the Poison Swamp"),
            ("Island in the Poison Swamp", "Sand Kingdom Timer Challenge 3"),
            ("Sand Kingdom Timer Challenge 3", "Wandering Cactus"),
            ("Wandering Cactus", "Jaxi Reunion!"),
            ("Jaxi Reunion!", "Mighty Leap from the Palm Tree!"),
            ("Mighty Leap from the Palm Tree!", "Where the Birds Gather"),
            ("Where the Birds Gather", "Fishing in the Oasis"),
            ("Fishing in the Oasis", "Taking Notes: Jump on the Palm"),
            ("Taking Notes: Jump on the Palm", "Taking Notes: In the Wall Painting"),
            ("Taking Notes: In the Wall Painting", "Secret of the Mural"),
            ("Secret of the Mural", "Peach in the Sand Kingdom"),
            ("Peach in the Sand Kingdom", "The Lurker Under the Stone"),
            ("The Lurker Under the Stone", "Welcome Back, Jaxi!"),
            ("Welcome Back, Jaxi!", "Found with Wooded Kingdom Art"),
            ("Found with Wooded Kingdom Art", "Among the Five Cactuses"),
            ("Among the Five Cactuses", "The Bullet Bill Maze: Side Path"),
            ("The Bullet Bill Maze: Side Path", "The Bullet Bill Maze: Break Through!"),
            ("The Bullet Bill Maze: Break Through!", "Sand Kingdom Timer Challenge 1"),
            ("Sand Kingdom Timer Challenge 1", "On the North Pillar"),
            ("On the North Pillar", "Skull Sign in the Transparent Maze"),
            ("Skull Sign in the Transparent Maze", "The Invisible Maze"),
            ("The Invisible Maze", "In the Skies Above the Canyon"),
            ("In the Skies Above the Canyon", "An invisible Gleam"),
            ("An invisible Gleam", "Found with Bowser's Kingdom Art"),
            ("Found with Bowser's Kingdom Art", "Sand Kingdom Timer Challenge 2"),
            ("Sand Kingdom Timer Challenge 2", "Into the Flowing Sands"),
            ("Into the Flowing Sands", "Alcove in the Ruins"),
            ("Alcove in the Ruins", "From a Crate In The Ruins"),
            ("From a Crate In The Ruins", "On the Lone Pillar")],
 "Metro 2": [("On the Lone Pillar", "Secret Path to New Donk City!"),
             ("Secret Path to New Donk City!", "Sphynx Traveling to the Waterfall"),
             ("Sphynx Traveling to the Waterfall", "City Gardening: Plaza Planter"),
             ("City Gardening: Plaza Planter", "Hat-and-Seek: In the City"),
             ("Hat-and-Seek: In the City", "Found with Seaside Kingdom Art"),
             ("Found with Seaside Kingdom Art", "Remotely Captured Car"),
             ("Remotely Captured Car", "Metro Kingdom Timer Challenge 3"),
             ("Metro Kingdom Timer Challenge 3", "Metro Kingdom Timer Challenge 1"),
             ("Metro Kingdom Timer Challenge 1", "Inside an Iron Girder"),
             ("Inside an Iron Girder", "Metro Kingdom Slots"),
             ("Metro Kingdom Slots", "City Gardening: Building Planter"),
             ("City Gardening: Building Planter", "Who Piled Garbage on This?"),
             ("Who Piled Garbage on This?", "Caught Hopping on a Building!"),
             ("Caught Hopping on a Building!", "Crossing Lines"),
             ("Crossing Lines", "Peach in the Metro Kingdom"),
             ("Peach in the Metro Kingdom", "Out of a Crate in the City"),
             ("Out of a Crate in the City", "Hat-and-Seek: In the Crowd"),
             ("Hat-and-Seek: In the Crowd", "Pushing Through the Crowd"),
             ("Pushing Through the Crowd", "High Over the Crowd"),
             ("High Over the Crowd", "Hidden in the Scrap"),
             ("Hidden in the Scrap", "Bird Traveling in the Park"),
             ("Bird Traveling in the Park", "Found in the Park! Good Dog!"),
             ("Found in the Park! Good Dog!", "Dizzying Heights"),
             ("Dizzying Heights", "Metro Kingdom Timer Challenge 2"),
             ("Metro Kingdom Timer Challenge 2", "How Do They Take Out the Trash?"),
             ("How Do They Take Out the Trash?", "Free Parking: Rooftop Hop"),
             ("Free Parking: Rooftop Hop", "Scaling Pitchblack Mountain"),
             ("Scaling Pitchblack Mountain", "Reaching Pitchblack Island"),
             ("Reaching Pitchblack Island", "Hanging Between Buildings"),
             ("Hanging Between Buildings", "Bird Traveling in the City"),
             ("Bird Traveling in the City", "One Man's Trash…"),
             ("One Man's Trash…", "Bullet Billding")],
 "Lake 2": [("Bullet Billding", "Secret Path to Lake Lamode!"),
            ("Secret Path to Lake Lamode!", "Lake Fishing"),
            ("Lake Fishing", "Taking Notes: Dive and Swim"),
            ("Taking Notes: Dive and Swim", "Behind the Floodgate"),
            ("Behind the Floodgate", "Bird Traveling Over the Lake"),
            ("Bird Traveling Over the Lake", "Love by the Lake"),
            ("Love by the Lake", "Waves of Poison: Hop to It!"),
            ("Waves of Poison: Hop to It!", "Waves of Poison: Hoppin' Over"),
            ("Waves of Poison: Hoppin' Over", "Lake Kingdom Timer Challenge 2"),
            ("Lake Kingdom Timer Challenge 2", "Peach in the Lake Kingdom"),
            ("Peach in the Lake Kingdom", "Found with Metro Kingdom Art"),
            ("Found with Metro Kingdom Art", "Our Secret Little Room"),
            ("Our Secret Little Room", "Deep, Deep Down"),
            ("Deep, Deep Down", "Let's Go Swimming, Captain Toad!"),
            ("Let's Go Swimming, Captain Toad!", "I Met a Lake Cheep Cheep!"),
            ("I Met a Lake Cheep Cheep!", "High-Flying Leap"),
            ("High-Flying Leap", "Rooftop of the Water Plaza"),
            ("Rooftop of the Water Plaza", "What's in the Box?"),
            ("What's in the Box?", "Jump, Grab, and Climb Some More"),
            ("Jump, Grab, and Climb Some More", "Jump, Grab, Cling, and Climb")],
 "Luncheon 2": [("Jump, Grab, Cling, and Climb", "Secret Path to Mount Volbono!"),
                ("Secret Path to Mount Volbono!", "A Tourist in the Luncheon Kingdom!"),
                ("A Tourist in the Luncheon Kingdom!", "Caught Hopping at the Volcano!"),
                ("Caught Hopping at the Volcano!", "Atop a Column in a Row"),
                ("Atop a Column in a Row", "Island of Salt Floating in the Lava"),
                ("Island of Salt Floating in the Lava", "Fork Flickin' Detour"),
                ("Fork Flickin' Detour", "Fork Flickin' to the Summit"),
                ("Fork Flickin' to the Summit", "By the Cannon Pointed at the Big Pot"),
                ("By the Cannon Pointed at the Big Pot", "On Top of a Tall, Tall Roof"),
                ("On Top of a Tall, Tall Roof", "Luncheon Kingdom Timer Challenge 3"),
                ("Luncheon Kingdom Timer Challenge 3", "Bon Appetit, Captain Toad!")],
 "Cap 2": [("Bon Appetit, Captain Toad!", "Hidden in a Sunken Hat"),
           ("Hidden in a Sunken Hat", "Bonnetter Blockade"),
           ("Bonnetter Blockade", "Cap Kingdom Timer Challenge 2"),
           ("Cap Kingdom Timer Challenge 2", "Shopping in Bonneton"),
           ("Shopping in Bonneton", "Precision Rolling"),
           ("Precision Rolling", "Roll On and On"),
           ("Roll On and On", "Good Evening, Captain Toad!"),
           ("Good Evening, Captain Toad!", "Fly to the Edge of the Fog"),
           ("Fly to the Edge of the Fog", "Under the Big One's Brim"),
           ("Under the Big One's Brim", "Cap Kingdom Timer Challenge 1"),
           ("Cap Kingdom Timer Challenge 1", "Peach in the Cap Kingdom"),
           ("Peach in the Cap Kingdom", "Fog-Shrouded Platform"),
           ("Fog-Shrouded Platform", "Spin the Hat, Get a Prize"),
           ("Spin the Hat, Get a Prize", "Found with Mushroom Kingdom Art"),
           ("Found with Mushroom Kingdom Art", "Next to Glasses Bridge"),
           ("Next to Glasses Bridge", "Taking Notes: In the Fog"),
           ("Taking Notes: In the Fog", "Danger Sign"),
           ("Danger Sign", "Bird Traveling in the Fog"),
           ("Bird Traveling in the Fog", "Caught Hopping Near the Ship!")],
 "Lost 2": [("Caught Hopping Near the Ship!", "Shopping on Forgotten Isle"),
            ("Shopping on Forgotten Isle", "Peach in the Lost Kingdom"),
            ("Peach in the Lost Kingdom", "Below the Cliff's Edge"),
            ("Below the Cliff's Edge", "Wrecked Rock Block"),
            ("Wrecked Rock Block", "Inside the Rising Stone Pillar"),
            ("Inside the Rising Stone Pillar", "Get Some Rest, Captain Toad"),
            ("Get Some Rest, Captain Toad", "Jump Down to the Top of a Tree"),
            ("Jump Down to the Top of a Tree", "Found with Snow Kingdom Art"),
            ("Found with Snow Kingdom Art", "Moon Shards in the Jungle"),
            ("Moon Shards in the Jungle", "Atop a Propeller Pillar"),
            ("Atop a Propeller Pillar", "Taking Notes: Stretch and Shrink"),
            ("Taking Notes: Stretch and Shrink", "Caught Hopping in the Jungle!"),
            ("Caught Hopping in the Jungle!", "A Propeller Pillar's Secret"),
            ("A Propeller Pillar's Secret", "Line It Up, Blow It Up"),
            ("Line It Up, Blow It Up", "The Shining Fruit"),
            ("The Shining Fruit", "Lost Kingdom Timer Challenge")],
 "Moon 2": [("Lost Kingdom Timer Challenge", "A Tourist in the Moon Kingdom"),
            ("A Tourist in the Moon Kingdom", "Found with Cap Kingdom Art"),
            ("Found with Cap Kingdom Art", "Thanks, Captain Toad!"),
            ("Thanks, Captain Toad!", "Shining Above the Moon"),
            ("Shining Above the Moon", "Sneaking Around in the Crater")],
 "Luncheon 3": [("Sneaking Around in the Crater", "Piled on the Salt"),
                ("Piled on the Salt", "Flying Over the Lava Islands"),
                ("Flying Over the Lava Islands", "Treasure of the Lava Islands"),
                ("Treasure of the Lava Islands", "Light the Two Flames"),
                ("Light the Two Flames", "Lurking in the Pillar's Shadow"),
                ("Lurking in the Pillar's Shadow", "Love Above the Lava"),
                ("Love Above the Lava", "From Inside a Bright Stone"),
                ("From Inside a Bright Stone", "Luncheon Kingdom Timer Challenge 2"),
                ("Luncheon Kingdom Timer Challenge 2", "Jammin' in the Luncheon Kingdom"),
                ("Jammin' in the Luncheon Kingdom", "Corner of the Magma Swamp"),
                ("Corner of the Magma Swamp", "Luncheon Kingdom Slots"),
                ("Luncheon Kingdom Slots", "Hat-and-Seek: Among the Food"),
                ("Hat-and-Seek: Among the Food", "Is This an Ingredient Too?!"),
                ("Is This an Ingredient Too?!", "Peach in the Luncheon Kingdom"),
                ("Peach in the Luncheon Kingdom", "Golden Turnip Recipe 1"),
                ("Golden Turnip Recipe 1", "Atop the Jutting Crag"),
                ("Atop the Jutting Crag", "From a Crack in the Hard Ground"),
                ("From a Crack in the Hard Ground", "Under the Meat Plateau"),
                ("Under the Meat Plateau", "Taking Notes: Swimming in Magma")],
 "Mushroom 2": [("Taking Notes: Swimming in Magma", "Secret Path to Peach's Castle!"),
                ("Secret Path to Peach's Castle!", "Jammin' in the Mushroom Kingdom"),
                ("Jammin' in the Mushroom Kingdom", "A Tourist in the Mushroom Kingdom"),
                ("A Tourist in the Mushroom Kingdom", "Shopping Near Peach's Castle"),
                ("Shopping Near Peach's Castle", "Forever Onward, Captain Toad!"),
                ("Forever Onward, Captain Toad!", "Caught Hopping at Peach's Castle!"),
                ("Caught Hopping at Peach's Castle!", "Gardening for Toad: Garden Seed"),
                ("Gardening for Toad: Garden Seed", "Gardening for Toad: Field Seed"),
                ("Gardening for Toad: Field Seed", "Grow a Flower Garden"),
                ("Grow a Flower Garden", "Mushroom Kingdom Timer Challenge"),
                ("Mushroom Kingdom Timer Challenge", "Toad Defender"),
                ("Toad Defender", "Love at Peach's Castle"),
                ("Love at Peach's Castle", "Perched on the Castle Roof")],
 "Toadette": [("Perched on the Castle Roof", "Rescue Princess Peach"),
              ("Rescue Princess Peach", "Achieve World Peace"),
              ("Achieve World Peace", "Power Moon Knight"),
              ("Power Moon Knight", "Power Moon Wizard"),
              ("Power Moon Wizard", "Flat Moon Finder"),
              ("Flat Moon Finder", "Treasure Chest Hunter"),
              ("Treasure Chest Hunter", "Note-Collecting World Tour"),
              ("Note-Collecting World Tour", "Timer Challenge Amateur"),
              ("Timer Challenge Amateur", "Timer Challenge Professional"),
              ("Timer Challenge Professional", "Captain Toad Meeter"),
              ("Captain Toad Meeter", "Captain Toad Greeter"),
              ("Captain Toad Greeter", "Touring with Princess Peach"),
              ("Touring with Princess Peach", "Globe-Trotting with Princess Peach"),
              ("Globe-Trotting with Princess Peach", "Gaga for Goombette"),
              ("Gaga for Goombette", "Lakitu Fishing Trip"),
              ("Lakitu Fishing Trip", "Flower-Growing Guru"),
              ("Flower-Growing Guru", "Running with Rabbits"),
              ("Running with Rabbits", "Racing with Rabbits"),
              ("Racing with Rabbits", "Ground Pound Instructor"),
              ("Ground Pound Instructor", "Ground Pound Professor"),
              ("Ground Pound Professor", "Rad Hatter"),
              ("Rad Hatter", "Super Rad Hatter"),
              ("Super Rad Hatter", "Traveling-Bird Herder"),
              ("Traveling-Bird Herder", "Hat-Seeking Missile"),
              ("Hat-Seeking Missile", "Art Enthusiast"),
              ("Art Enthusiast", "Slots Machine"),
              ("Slots Machine", "Capturing Novice"),
              ("Capturing Novice", "Capturing Apprentice"),
              ("Capturing Apprentice", "World Warper"),
              ("World Warper", "Checkpoint Flagger"),
              ("Checkpoint Flagger", "Loaded with Coins")],
 "Darker Side": [("Loaded with Coins", "Long Journey's End")]}

if __name__ == "__main__":
    for key, value in ROUTE.items():
        print(key)